### ISSUE TITLE
Плотность солей в концентратах.

### ISSUE THREAD

**Issue by dipgrog** [siv237/HPG#11]
Концентраты - Расчет -  Раствор А и Раствор Б  - колонка плотность [г/мл] считается только при изменении значений
в колонке [г/л], то есть, если колонку [г/л] не трогать, то плотность [г/мл] останется по умолчанию 1г/мл и для расчета веса жидкостей [гр.жидк.] для миксера будут переданы неверные значения, что приведет к изготовлению ошибочных концентратов с неправильным весом.

**Comment by siv237** [comment]
это не ошибка. Суть в том что плотность это измеряемая фактическая величина и вносится вручную. Расчет делается лишь для проверки примерной сходимости и оценки соответствия вещества теории
