### ISSUE TITLE
В архиве examplpes.zip сбилась кодировка файлов

### ISSUE THREAD

**Issue by zakamik** [siv237/HPG#13]
Проверено в Windows и linux - русские название файлов нечитабельны:

![изображение](https://user-images.githubusercontent.com/9119743/182570951-e8fa9a26-64d0-4821-a83c-a688a30412e7.png)

**Comment by siv237** [comment]
@zakamik Проверено на телефоне и так же на macOSx
Проблема на твоей стороне

<img width="340" alt="image" src="https://user-images.githubusercontent.com/13055750/182606488-534d2107-302e-4f8f-8f7c-8dbe703b4c15.png"><img width="260" alt="image" src="https://user-images.githubusercontent.com/13055750/182606674-d9deb719-491c-4301-ad43-f445edcc3533.png">

**Comment by GuestEG** [comment]
При распаковке WinRAR - кодировка ломается.
При распаковке ZIP - не ломается.,

Win10, PC.

**Comment by zakamik** [comment]
Windows 10 - zip кодировка ломается
Windows 10 7zip - ломается
Windows 10 Far - ломается
Debian 10 plasma - mc - ломается
Android 11 - RAR - ломается
Android 11 встроенный просмотр файлов - работает

всё-таки что-то не так с кодировкой.

**Comment by kkirpichnikov** [comment]
@zakamik можешь, пожалуйста, проверить еще раз.
Попробовал использовать другой архиватор.

**Comment by zakamik** [comment]
В Windows теперь всё отлично, спасибо! Остальное проверю позже. Если будут проблемы, напишу
