### ISSUE TITLE
Error: Invalid floating point operation Версия 0.200 Win10 

### ISSUE THREAD

**Issue by chesaregel** [siv237/HPG#3]
При запуске приложения и попытке открытия сохранённого файла появляется ошибка, и не позволяет работать дальше.

![image](https://user-images.githubusercontent.com/32063045/101241321-9f2bb680-36fd-11eb-841c-468dea2c8ef7.png)

**Comment by VisualGadget** [comment]
Добрый день!

У меня было то же самое просто при старте приложения v0.200. Вылечил удалением профиля default.hpg. Вот тот проблемный профиль.
[default.zip](https://github.com/siv237/HPG/files/5663824/default.zip)

**Comment by siv237** [comment]
Да проблемы синтакиса файла записи не проверяются пока.
