### ISSUE TITLE
Ошибка при сохранении после подгрузки профиля

### ISSUE THREAD

**Issue by Apkawa** [siv237/HPG#5]
1) Открываем свой профиль со своими удобрениями, допустим - "Перец.hpg"
2) Подгружаем другой профиль из другого профиля, например, профиль вадима (Файл, Подгрузить профиль)
3) Путь к профилю остается прежним как в п1 
4) Нажимаем "сохранить" (внизу напротив объема)

Ожидалось:

сохраняется в свой профиль, путь до профиля дб как в п1.

Результат:

профиль сохраняется в профиль вадима из примера, путь к профилю меняется до профиля вадима

воспроизводится в версии 0.212

**Comment by siv237** [comment]
Спасибо исправлено в версии 0.213
