### ISSUE TITLE
Обнуление профиля

### ISSUE THREAD

**Issue by Apkawa** [siv237/HPG#6]
Иногда требуется скопировать какой то профиль либо по граммам либо по ppm либо по соотношениям, но перед этим удобнее обнулить все макро и соотношения.

Сейчас это делается несколько сложно и периодически начинает все равно крутить то одно то другое, предлагаю добавить какую то кнопку которая делает сразу 3 вещи

1) Обнуляет профиль
2) Обнуляет все соотношения
3) Обнуляет всю навеску

Микро можно не трогать, скорее всего.

**Comment by siv237** [comment]
при работе с нулями и близкими к ним значениями имеются множественные проблемы связанные с с делением на 0 и сверхбольшими числами, текущая математическая модель основанная на решении системы уравнений не будет работать устойчиво.
